# Please keep AllCops, Bundler, Style, Metrics groups and then order cops
# alphabetically
inherit_from:
  - https://raw.githubusercontent.com/hanami/devtools/1.3.x/.rubocop.yml
Naming/MethodParameterName:
  AllowedNames:
    - ci
    - db
    - id
    - os
Layout/LineLength:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  PreferredName: "exception"
Style/RescueStandardError:
  Enabled: false
Style/DateTime:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.6
